# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
import os
import sys


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(449, 206)
        Widget.setAutoFillBackground(False)
        self.runb = QtWidgets.QPushButton(parent=Widget)
        self.runb.setGeometry(QtCore.QRect(310, 160, 121, 41))
        self.runb.setObjectName("runb")
        self.runb.clicked.connect(self.runit)
        self.nuhuh = QtWidgets.QPushButton(parent=Widget)
        self.nuhuh.setGeometry(QtCore.QRect(180, 160, 121, 41))
        self.nuhuh.setObjectName("nuhuh")
        self.webb = QtWidgets.QPushButton(parent=Widget)
        self.webb.setGeometry(QtCore.QRect(10, 160, 161, 41))
        self.nuhuh.clicked.connect(sys.exit)
        self.webb.setObjectName("webb")
        self.webb.clicked.connect(self.webrun)
        self.label = QtWidgets.QLabel(parent=Widget)
        self.label.setGeometry(QtCore.QRect(10, 0, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Inter ExtraLight")
        font.setPointSize(35)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Widget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 421, 19))
        self.label_2.setObjectName("label_2")
        self.inout = QtWidgets.QLineEdit(parent=Widget)
        self.inout.setGeometry(QtCore.QRect(0, 80, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Droid Sans")
        self.inout.setFont(font)
        self.inout.setObjectName("inout")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Run"))
        self.runb.setText(_translate("Widget", "Run"))
        self.nuhuh.setText(_translate("Widget", "Cancel"))
        self.webb.setText(_translate("Widget", "Run from web"))
        self.label.setText(_translate("Widget", "Run"))
        self.label_2.setText(_translate("Widget", "Type a command or a script to run it"))
    def runit(self):
        self.cmd = self.inout.text()
        os.system(self.cmd)
        sys.exit()

    def webrun(self):
        self.cmd = self.inout.text()
        os.system(f'curl {self.cmd} | bash')
        sys.exit()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec())
